spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hellojpa?serverTimezone=UTC&characterEncoding=UTF-8&allowMultiQueries=true
    username: user
    password: user
    maximumPoolSize: 20
    leak-detection-threshold: 0

  jpa:
    hibernate:
      naming_strategy: org.hibernate.cfg.EJB3NamingStrategy